### ISSUE TITLE
scripts don't work if build paths have spaces

### ISSUE THREAD

**Issue by chillpop** [vokal/XcodeCoverage#4]
A whole bunch of quoting is needed.  This isn't an issue on Travis, but if try to run the scripts locally for testing, you might have paths with spaces.

**Comment by designatednerd** [comment]
@chillpop Have you been able to determine whether this is an issue from the upstream repo or whether it's exclusive to our repo?

**Comment by chillpop** [comment]
I think it's mostly from the upstream repo.  All of the `source` lines should have their paths quoted.  
However, this unquoted path is only is our fork: https://github.com/vokal/XcodeCoverage/blob/master/envcov.sh#L13

**Comment by designatednerd** [comment]
Fixed by #5.
